version: 2
updates:
  - package-ecosystem: npm
    directory: "/extension"
    schedule:
      interval: monthly
    groups:
      security:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: monthly
    groups:
      security:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: cargo
    directory: "/server"
    schedule:
      interval: monthly
    groups:
      security:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
