version: 2
updates:
  - package-ecosystem: npm
    directory: "/extension"
    schedule:
      interval: monthly
    groups:
      security:
        dependency-type: production
        update-types:
          - minor
          - patch
      major:
        dependency-type: production
        update-types:
          - major
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: monthly
    groups:
      security:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
