version: 2
updates:
  - package-ecosystem: npm
    directory: "/extension"
    schedule:
      interval: monthly
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
