name: "CI"
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install

      - name: Check types
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install

      - name: Build extension
        run: pnpm run build:plasmo
