name: "CI"
on:
  push:

env:
  NODE_VERSION: 22

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install

      - name: Run all tests
        run: pnpm run test

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Check types
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

  website:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
