name: "Web Store Submission"
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  NODE_VERSION: 22.22

defaults:
  run:
    working-directory: extension

jobs:
  submit:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: extension/package.json
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager-cache: false
      - run: pnpm install

      - name: Package into zip artifact
        env:
          PUBLIC_MAIN_URL: https://peekforynab.com
        run: pnpm run build:zip

      - name: Submit to stores
        run: pnpm wxt submit --chrome-zip build/*-chrome.zip
        ## --firefox-zip build/*-firefox.zip --firefox-sources-zip build/*-sources.zip
        env:
          CHROME_PUBLISH_TARGET: "default"
          CHROME_SKIP_SUBMIT_REVIEW: "false"
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          working_directory: extension
          files: build/*-chrome.zip
          generate_release_notes: true
          make_latest: true
