name: "Web Store Submission"
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  NODE_VERSION: 22.22

defaults:
  run:
    working-directory: extension

jobs:
  submit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: extension/package.json
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager-cache: false
      - run: pnpm install

      - name: Package into zip artifact
        env:
          PUBLIC_MAIN_URL: https://peek-for-ynab-v2.fly.dev
          PUBLIC_YNAB_CLIENT_ID: MXlSSQTLehZOIlzmsasuCpoGb9wvnxH5lmZBwxbPFnY
        run: pnpm run build:zip

      - name: Submit to stores
        run: pnpm wxt submit --chrome-zip build/*-chrome.zip
        ## --firefox-zip build/*-firefox.zip --firefox-sources-zip build/*-sources.zip
        env:
          CHROME_PUBLISH_TARGET: "default"
          CHROME_SKIP_SUBMIT_REVIEW: "false"
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
